"""empty message

Revision ID: ad09bba9ece0
Revises: 
Create Date: 2026-03-20 10:04:49.186252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad09bba9ece0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('salon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('salon_materia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('salon_materia_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.ForeignKeyConstraint(['salon_materia_id'], ['salon_materia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificacion')
    op.drop_table('salon_materia')
    op.drop_table('alumno')
    op.drop_table('salon')
    op.drop_table('user')
    op.drop_table('profesor')
    op.drop_table('materia')
    # ### end Alembic commands ###
